# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 654ab7ac9c3411ce435eb7c29d587462854f1497451531f1571f843be7759df44340a38c1a9ff3090e66ba11df97edc4850039587d16fa314a8e9b8ad2df51a6

test:
  secret_key_base: 730c7d6771483df950acb3ab6664060a5366b014398eaf5b229f46463f590430fa62e459ec32838eb6c8efb9f99e0c48897ab20322006c312502b8b053014d2d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
